"""Real `verify.compare()` output for the Check screen to render.

A mockup that invents its own results is only testing my imagination. These
come from the engine: two decks are built from the **synthetic demo template**
and compared, so the shape, the field names and the wording are exactly what
the real screen will receive - and unlike the payload catalogue, this output is
committable, because nothing in the demo template is confidential.

Three cases, because a Check screen that has only ever been drawn against a
failure is as untested as one only drawn against a pass:

    identical      -> the answer an author hopes for
    text only      -> right slides, right order, wrong values
    selection      -> a slide missing, which is the real failure

    python tools/make_ui_check_samples.py
"""
import argparse
import json
import os
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

from engine import Template, build_template                   # noqa: E402
from engine.verify import block_names, compare                # noqa: E402


def one(tpl, tmp, label, note, templafy_answers, our_answers):
    a = os.path.join(tmp, label + "_templafy.pptx")
    b = os.path.join(tmp, label + "_ours.pptx")
    build_template(tpl, templafy_answers, a)
    build_template(tpl, our_answers, b)
    result = compare(a, b, names=block_names(tpl))
    # trim the long tails: a screen shows the first few and says how many more
    result["text_differs"] = [
        {k: (v[:8] if isinstance(v, list) and k.startswith("only_in") else v)
         for k, v in d.items()} for d in result["text_differs"][:6]]
    return {"label": label, "note": note,
            "ours": os.path.basename(b), "templafy": os.path.basename(a),
            "result": result}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--template", default=os.path.join(HERE, "..", "templates", "demo"))
    ap.add_argument("--out", default=os.path.join(HERE, "..", "ui", "check_samples.js"))
    args = ap.parse_args(argv)

    tpl = Template(args.template)
    base = json.load(open(os.path.join(tpl.folder, "answers.baseline.json"),
                          encoding="utf-8"))
    exp = json.load(open(os.path.join(tpl.folder, "answers.expansion.json"),
                         encoding="utf-8"))
    # same slides, different client: isolates text from selection
    text_only = dict(exp)
    for field in ("FullClientName", "ShortClientName", "DueDate", "City"):
        if field in base:
            text_only[field] = base[field]

    tmp = tempfile.mkdtemp(prefix="pptgen2_checksample_")
    try:
        cases = [
            one(tpl, tmp, "identical",
                "the same answers on both sides", exp, exp),
            one(tpl, tmp, "text_only",
                "right slides, right order, different client details",
                exp, text_only),
            one(tpl, tmp, "selection",
                "built from the wrong answers - a slide is missing", exp, base),
        ]
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    out = os.path.abspath(args.out)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/make_ui_check_samples.py.\n"
                 "   Real engine output from the synthetic demo template -\n"
                 "   safe to commit, and it keeps the Check screen honest about\n"
                 "   what verify.compare() actually returns. */\n")
        fh.write("window.CHECK_SAMPLES = ")
        json.dump(cases, fh, indent=1, ensure_ascii=False)
        fh.write(";\n")

    print("Wrote %s" % out)
    for c in cases:
        r = c["result"]
        print("  %-10s %-26s %d vs %d slides, %d matched (%s)"
              % (c["label"], r["verdict"], r["our_slides"], r["templafy_slides"],
                 r["matched"],
                 ", ".join("%s %d" % kv for kv in sorted(r["by_method"].items()))
                 or "-"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
