"""Working out *why* each slide was in a deck, and proposing rules from it.

When a library is merged from decks generated by answering a form, the evidence
for the rules is already there: a slide that appears in exactly the decks where
`Peer_review` is true is almost certainly controlled by that answer. The
payloads are OFAT — one field changed at a time — which makes that inference
unusually clean.

It is still **a proposal, not a conclusion**. Anything no single answer explains
is left in the baseline and flagged, because a confident wrong rule is worse
than an obvious gap. The author confirms each one (workflow step 3).

`propose_from_provenance()` works off `provenance.json`, so the rules can be
rebuilt for a template that already exists — without re-running the merge and
risking the library.
"""
import json
import os
import re

from .library import Library


def flatten(obj, prefix=""):
    out = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.update(flatten(v, "%s.%s" % (prefix, k) if prefix else str(k)))
    else:
        out[prefix] = obj
    return out


def norm(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    return re.sub(r"\s+", " ", str(value)).strip()


def load_payloads(folder, deck_labels):
    """Pair each deck with its payload by file name (`01_x.pptx` <- `01_x.json`,
    or a shared numeric prefix)."""
    if not folder or not os.path.isdir(folder):
        return {}, list(deck_labels)
    files = {os.path.splitext(f)[0]: os.path.join(folder, f)
             for f in os.listdir(folder) if f.endswith(".json")}
    by_prefix = {}
    for stem in files:
        m = re.match(r'(\d+)', stem)
        if m:
            by_prefix.setdefault(m.group(1), stem)

    paired, unpaired = {}, []
    for label in deck_labels:
        stem = label if label in files else None
        if stem is None:
            m = re.match(r'(\d+)', label)
            if m and m.group(1) in by_prefix:
                stem = by_prefix[m.group(1)]
        if stem is None:
            unpaired.append(label)
            continue
        with open(files[stem], encoding="utf-8") as fh:
            paired[label] = json.load(fh)
    return paired, unpaired


def propose_conditions(block_decks, payloads):
    """block id -> the answer that explains it. -> (proposals, notes)

    `block_decks` is {block id: [deck labels it appeared in]}.
    """
    all_decks = set()
    for decks in block_decks.values():
        all_decks.update(decks)
    all_decks &= set(payloads)
    if not all_decks:
        return {}, ["no deck could be paired with a payload"]

    # (field, value) -> the decks whose payload has it
    by_value = {}
    for deck in all_decks:
        for field, value in flatten(payloads[deck]).items():
            by_value.setdefault((field, norm(value)), set()).add(deck)
    # a field that never varies explains nothing, even if the sets match
    varies = {f for f in {k[0] for k in by_value}
              if len({norm(flatten(p).get(f)) for p in payloads.values()}) > 1}

    proposals, notes = {}, []
    for bid, decks in block_decks.items():
        present = set(decks) & all_decks
        if present == all_decks or not present:
            continue                                  # in every deck: baseline
        matches = sorted((f, v) for (f, v), d in by_value.items()
                         if d == present and f in varies)
        if len(matches) == 1:
            field, value = matches[0]
            proposals[bid] = {"field": field, "value": value,
                              "decks": sorted(present)}
        elif matches:
            proposals[bid] = {"field": matches[0][0], "value": matches[0][1],
                              "decks": sorted(present),
                              "ambiguous": ["%s=%s" % m for m in matches[:6]]}
            notes.append("%s: %d answers explain it equally well (%s) - picked "
                         "the first; confirm which is right"
                         % (bid, len(matches),
                            ", ".join("%s=%s" % m for m in matches[:3])))
        else:
            notes.append("%s: appears in %d of %d decks but no single answer "
                         "explains it - left in the baseline, needs a human"
                         % (bid, len(present), len(all_decks)))
    return proposals, notes


def derive_anchors(order, block_decks):
    """block id -> the block it should follow, from the library's own order.

    A conditional block has to say where it slots back in, or the builder can
    only append it. The library holds the slides in the order the decks had
    them, so the block just before it is where it sat.

    The anchor must be present *whenever this block is*, or it vanishes exactly
    when it is needed — so we walk back to the nearest earlier block whose set
    of decks is a superset of this one's.
    """
    anchors = {}
    for i, bid in enumerate(order):
        mine = set(block_decks.get(bid) or [])
        for earlier in reversed(order[:i]):
            if set(block_decks.get(earlier) or []) >= mine:
                anchors[bid] = earlier
                break
    return anchors


def recover_anchors(template, decks_dir):
    """Read the original decks to learn where each block actually sat.

    The library cannot tell us: a block a later deck introduced sits at the end
    of it, wherever it sat in its own deck. Only the decks know the order, so
    when `provenance.json` predates the merge recording anchors, this recovers
    them — without rebuilding the library, which is the part that is hard to
    get right and easy to break.

    Slides are matched to blocks the same way the merge matched them across
    decks: by their shape creationIds.
    """
    import glob
    from .identity import geometry_key, slide_identity

    # Two keys, because tokenising rewrites the very text a slide is
    # recognised by: creationIds where the decks have them, shape geometry
    # otherwise. Geometry does not move when text is substituted.
    with template.open_library() as lib:
        by_identity, geo_seen = {}, {}
        for block in lib.ordered():
            raw = lib.read_bytes(block.part)
            key, _how = slide_identity(raw)
            by_identity.setdefault(key, block.id)
            geo = geometry_key(raw)
            if geo:
                geo_seen.setdefault(geo, []).append(block.id)
    # Geometry is a fallback, not an identity: slides built from one layout
    # share it. Keep only the keys that name exactly one block - a wrong match
    # here would put a block in the wrong place, quietly.
    by_geometry = {geo: ids[0] for geo, ids in geo_seen.items() if len(ids) == 1}

    decks = sorted(glob.glob(os.path.join(str(decks_dir), "*.pptx")))
    decks = [d for d in decks if not os.path.basename(d).startswith("~$")]
    orders, unreadable = [], []
    matched = unmatched = 0
    for path in decks:
        try:
            with Library(path) as deck:
                order = []
                for part in deck.slide_parts:
                    raw = deck.read_bytes(part)
                    key, _how = slide_identity(raw)
                    bid = by_identity.get(key)
                    if bid is None:
                        geo = geometry_key(raw)
                        bid = by_geometry.get(geo) if geo else None
                    if bid is None:
                        unmatched += 1
                        continue
                    matched += 1
                    if bid not in order:
                        order.append(bid)
                if order:
                    orders.append(order)
        except Exception as exc:
            unreadable.append("%s: %s" % (os.path.basename(path), exc))
    return orders, unreadable, {"matched": matched, "unmatched": unmatched,
                                "decks": len(decks)}


def anchors_from_deck_orders(orders, block_decks):
    """block id -> the block it followed, from the decks' own slide order.

    The anchor has to be present whenever the block is, or it disappears
    exactly when it is needed — so we walk back to the nearest earlier block
    whose set of decks is a superset of this one's. The first deck that shows a
    block decides its anchor, matching what the merge itself does.
    """
    anchors = {}
    for order in orders:
        for i, bid in enumerate(order):
            if bid in anchors:
                continue
            mine = set(block_decks.get(bid) or [])
            for earlier in reversed(order[:i]):
                if set(block_decks.get(earlier) or []) >= mine:
                    anchors[bid] = earlier
                    break
    return anchors


def consensus_order(orders, fallback):
    """Order the blocks the way the decks themselves order them.

    The library's order is an artifact of the merge, not evidence. A block a
    later deck introduced lands wherever the merge put it, which need not be
    where any deck had it -- and one block sitting a few places off is invisible
    in the library while showing up as "1 slide out of order" on every single
    deck, baseline included. That is not a conditional-block problem, so no
    amount of fixing `insert_after` touches it.

    The decks are the authority. Each deck orders the blocks it contains; taken
    together they are a precedence graph, and a topological sort of it is an
    order every deck agrees with. Where the decks say nothing -- two blocks that
    never appear in the same deck -- `fallback` (the library) breaks the tie, so
    the result stays deterministic.

    If the decks genuinely disagree, the graph has a cycle. We break it by
    falling back for that one choice rather than failing: a slightly wrong order
    is reportable by `verify`, while a crash leaves the author with nothing.
    """
    rank = {bid: i for i, bid in enumerate(fallback)}
    after = {bid: set() for bid in fallback}      # bid -> blocks that precede it
    for order in orders:
        known = [b for b in order if b in rank]
        for i, earlier in enumerate(known):
            for later in known[i + 1:]:
                after[later].add(earlier)

    out, placed = [], set()
    remaining = set(fallback)
    while remaining:
        ready = [b for b in remaining if not (after[b] - placed)]
        if not ready:
            # the decks contradict each other here; take the library's word for
            # this one block and carry on, so the disagreement costs one
            # position rather than the whole ordering
            ready = list(remaining)
        pick = min(ready, key=lambda b: rank[b])
        out.append(pick)
        placed.add(pick)
        remaining.discard(pick)
    return out

def propose_from_provenance(template, payloads_dir, decks_dir=None):
    """Rebuild rules.json for a merged template. -> report dict.

    Existing placeholder bindings are preserved: they come from tokenising the
    library and have nothing to do with slide selection. Losing them would turn
    a working template back into one client's snapshot.
    """
    prov_path = os.path.join(template.folder, "provenance.json")
    if not os.path.exists(prov_path):
        raise ValueError("no provenance.json - this template was not merged "
                         "from generated decks, so there is no evidence to "
                         "propose rules from")
    with open(prov_path, encoding="utf-8") as fh:
        prov = json.load(fh)
    blocks = prov.get("blocks") or {}
    if not blocks:
        raise ValueError("provenance.json records no blocks")

    with template.open_library() as lib:
        order = [b.id for b in lib.ordered()]
    known = set(order)
    block_decks = {bid: info.get("decks") or []
                   for bid, info in blocks.items() if bid in known}
    stale = sorted(set(blocks) - known)

    labels = sorted({d for decks in block_decks.values() for d in decks})
    payloads, unpaired = load_payloads(payloads_dir, labels)
    proposals, notes = propose_conditions(block_decks, payloads)

    # Prefer the anchor the merge recorded: it came from each deck's own slide
    # order. Falling back to library order is a guess, because a block a later
    # deck introduced sits at the end of the library wherever it sat in its
    # deck - so say so rather than presenting it as evidence.
    recorded = {bid: (blocks[bid] or {}).get("after")
                for bid in block_decks if (blocks[bid] or {}).get("after")}
    recovered, unreadable, matching, reordered = {}, [], None, 0
    if decks_dir:
        # the decks themselves are the authority, and reading them costs
        # nothing next to rebuilding the library
        orders, unreadable, matching = recover_anchors(template, decks_dir)
        recovered = anchors_from_deck_orders(orders, block_decks)
        # ...for the baseline's own order too, not only for the anchors. The
        # baseline is every deck's spine, so a block out of place in it is out
        # of place in every deck we build.
        consensus = consensus_order(orders, order)
        reordered = sum(1 for a, b in zip(order, consensus) if a != b)
        order = consensus
    anchors = derive_anchors(order, block_decks)
    anchors.update(recovered)
    anchors.update(recorded)
    from_decks = set(recorded) | set(recovered)

    baseline = [bid for bid in order if bid not in proposals]
    rule_blocks, unanchored = {}, []
    for bid in order:
        if bid not in proposals:
            continue
        info = proposals[bid]
        spec = {"slides": [bid],
                "when": {"field": info["field"], "eq": info["value"]},
                "_evidence": "in %d deck(s): %s"
                             % (len(info["decks"]), ", ".join(info["decks"][:4]))}
        anchor = anchors.get(bid)
        if anchor and (anchor in baseline or anchor in proposals):
            spec["insert_after"] = anchor
            if bid not in from_decks:
                spec["_confirm_position"] = (
                    "placed from library order, not from the decks - check it "
                    "sits where it should")
        else:
            unanchored.append(bid)
        if info.get("ambiguous"):
            spec["_confirm"] = ("equally explained by: %s"
                                % ", ".join(info["ambiguous"]))
        rule_blocks[bid] = spec

    existing = {}
    if os.path.exists(template.rules_path):
        with open(template.rules_path, encoding="utf-8") as fh:
            existing = json.load(fh)

    rules = dict(existing)
    rules.update({
        "name": existing.get("name", template.name),
        "library": existing.get("library", os.path.basename(template.library_path)),
        "_comment": ("Baseline = slides present in every deck. Blocks with a "
                     "`when` are PROPOSED from which decks contained them - "
                     "confirm each before trusting it. Evidence: "
                     "provenance.json."),
        "baseline": baseline,
        "blocks": rule_blocks,
    })
    rules.setdefault("placeholders", existing.get("placeholders", {}))
    with open(template.rules_path, "w", encoding="utf-8") as fh:
        json.dump(rules, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    return {"baseline": len(baseline), "conditional": len(rule_blocks),
            "unanchored": unanchored, "unpaired_decks": unpaired,
            "stale_blocks": stale, "notes": notes,
            "reordered": reordered,
            "anchors_from_decks": sum(1 for b in rule_blocks if b in from_decks),
            "anchors_guessed": sum(1 for b in rule_blocks
                                   if b not in from_decks and b not in unanchored),
            "unreadable_decks": unreadable, "deck_matching": matching,
            "placeholders_kept": len(rules.get("placeholders") or {})}
