/* Generated by tools/make_ui_check_samples.py.
   Real engine output from the synthetic demo template -
   safe to commit, and it keeps the Check screen honest about
   what verify.compare() actually returns. */
window.CHECK_SAMPLES = [
 {
  "label": "identical",
  "note": "the same answers on both sides",
  "ours": "identical_ours.pptx",
  "templafy": "identical_templafy.pptx",
  "result": {
   "verdict": "MATCH",
   "order_ok": true,
   "out_of_order": 0,
   "templafy_slides": 8,
   "our_slides": 8,
   "matched": 8,
   "by_method": {
    "structural": 8
   },
   "displaced": [],
   "missing": [],
   "extra": [],
   "data_driven": 0,
   "text_differs": [],
   "selection_ok": true,
   "exact": true
  }
 },
 {
  "label": "text_only",
  "note": "right slides, right order, different client details",
  "ours": "text_only_ours.pptx",
  "templafy": "text_only_templafy.pptx",
  "result": {
   "verdict": "SELECTION OK, TEXT DIFFERS",
   "order_ok": true,
   "out_of_order": 0,
   "templafy_slides": 8,
   "our_slides": 8,
   "matched": 8,
   "by_method": {
    "structural": 8
   },
   "displaced": [],
   "missing": [],
   "extra": [],
   "data_driven": 0,
   "text_differs": [
    {
     "templafy_index": 1,
     "ours_index": 1,
     "only_in_templafy": [
      "15",
      "april",
      "globex",
      "holdings",
      "international"
     ],
     "only_in_ours": [
      "30",
      "manufacturing",
      "northwind",
      "november",
      "plc"
     ],
     "segments": [
      {
       "ours": "Northwind Manufacturing plc",
       "templafy": "Globex International Holdings"
      },
      {
       "ours": "November 30,",
       "templafy": "April 15,"
      }
     ]
    },
    {
     "templafy_index": 6,
     "ours_index": 6,
     "only_in_templafy": [
      "globex",
      "holdings",
      "international"
     ],
     "only_in_ours": [
      "manufacturing",
      "northwind",
      "plc"
     ],
     "segments": [
      {
       "ours": "Northwind Manufacturing plc.",
       "templafy": "Globex International Holdings."
      }
     ]
    },
    {
     "templafy_index": 8,
     "ours_index": 8,
     "only_in_templafy": [
      "15",
      "april",
      "new",
      "york"
     ],
     "only_in_ours": [
      "30",
      "manchester",
      "november"
     ],
     "segments": [
      {
       "ours": "Manchester",
       "templafy": "New York"
      },
      {
       "ours": "November 30,",
       "templafy": "April 15,"
      }
     ]
    }
   ],
   "selection_ok": true,
   "exact": false
  }
 },
 {
  "label": "selection",
  "note": "built from the wrong answers - a slide is missing",
  "ours": "selection_ours.pptx",
  "templafy": "selection_templafy.pptx",
  "result": {
   "verdict": "SELECTION DIFFERS",
   "order_ok": true,
   "out_of_order": 0,
   "templafy_slides": 8,
   "our_slides": 7,
   "matched": 7,
   "by_method": {
    "structural": 7
   },
   "displaced": [],
   "missing": [
    {
     "index": 7,
     "preview": "Proposed fees Phase Timing Fee Planning & risk assessment Q1 $48,000 I"
    }
   ],
   "extra": [],
   "data_driven": 0,
   "text_differs": [
    {
     "templafy_index": 1,
     "ours_index": 1,
     "only_in_templafy": [
      "15",
      "april",
      "globex",
      "holdings",
      "international"
     ],
     "only_in_ours": [
      "30",
      "manufacturing",
      "northwind",
      "november",
      "plc"
     ],
     "segments": [
      {
       "ours": "Northwind Manufacturing plc",
       "templafy": "Globex International Holdings"
      },
      {
       "ours": "November 30,",
       "templafy": "April 15,"
      }
     ]
    },
    {
     "templafy_index": 5,
     "ours_index": 5,
     "only_in_templafy": [
      "a",
      "across",
      "and",
      "applies",
      "beyond",
      "covering",
      "current",
      "effort"
     ],
     "only_in_ours": [
      "audit",
      "charged",
      "financial",
      "for",
      "governance",
      "information",
      "interim",
      "manufacturing"
     ],
     "segments": [
      {
       "ours": "Scope",
       "templafy": "Expansion"
      },
      {
       "ours": "work",
       "templafy": "services"
      },
      {
       "ours": "Audit of",
       "templafy": "Transition planning across"
      },
      {
       "ours": "statutory financial statements for Northwind Manufacturing plc.",
       "templafy": "newly in-scope entities."
      },
      {
       "ours": "Review of",
       "templafy": "A single reporting timetable covering"
      }
     ]
    },
    {
     "templafy_index": 6,
     "ours_index": 6,
     "only_in_templafy": [
      "acquired",
      "auditor",
      "charged",
      "component",
      "consolidation",
      "each",
      "expanded",
      "financial"
     ],
     "only_in_ours": [
      "000",
      "126",
      "171",
      "345",
      "48",
      "are",
      "assessment",
      "end"
     ],
     "segments": [
      {
       "ours": "Proposed fees Phase Timing Fee Planning & risk assessment Q1 $48,000 Interim fieldwork Q2–Q3 $126,000 Year-end audit & reporting Q4 $171,000 Total $345,000 Fees are exclusive",
       "templafy": "Scope"
      },
      {
       "ours": "VAT",
       "templafy": "work — expanded • Audit of the statutory financial statements for Globex International Holdings. • Audit of each newly acquired subsidiary in the expanded group. • Group consolidation"
      },
      {
       "ours": "out-of-pocket expenses.",
       "templafy": "component auditor instructions. • Reporting to those charged with governance."
      }
     ]
    },
    {
     "templafy_index": 8,
     "ours_index": 7,
     "only_in_templafy": [
      "15",
      "april",
      "new",
      "york"
     ],
     "only_in_ours": [
      "30",
      "manchester",
      "november"
     ],
     "segments": [
      {
       "ours": "Manchester",
       "templafy": "New York"
      },
      {
       "ours": "November 30,",
       "templafy": "April 15,"
      }
     ]
    }
   ],
   "selection_ok": false,
   "exact": false
  }
 }
];
